esphome:
  name: esp_dsmr
  platform: ESP8266
  board: d1_mini_lite
  includes:
    - dsmr_p1_uart.h
  libraries:
    - "Dsmr"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp_dsmr_fallback"
    password: ""

captive_portal:

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

uart:
  - rx_pin: GPIO3
    baud_rate: 115200
    id: uart_bus

sensor:
  - platform: custom
    lambda: |-
      auto dsmr_p1_sensor = new CustomP1UartComponent(id(uart_bus));
      App.register_component(dsmr_p1_sensor);
      return {dsmr_p1_sensor->s_energy_delivered_tariff1, dsmr_p1_sensor->s_energy_delivered_tariff2, dsmr_p1_sensor->s_energy_returned_tariff1, dsmr_p1_sensor->s_energy_returned_tariff2, dsmr_p1_sensor->s_power_delivered, dsmr_p1_sensor->s_power_returned, dsmr_p1_sensor->s_voltage_l1, dsmr_p1_sensor->s_voltage_l2, dsmr_p1_sensor->s_voltage_l3, dsmr_p1_sensor->s_current_l1, dsmr_p1_sensor->s_current_l2, dsmr_p1_sensor->s_current_l3, dsmr_p1_sensor->s_power_delivered_l1, dsmr_p1_sensor->s_power_delivered_l2, dsmr_p1_sensor->s_power_delivered_l3, dsmr_p1_sensor->s_power_returned_l1, dsmr_p1_sensor->s_power_returned_l2, dsmr_p1_sensor->s_power_returned_l3, dsmr_p1_sensor->s_gas_device_type, dsmr_p1_sensor->s_gas_valve_position, dsmr_p1_sensor->s_gas_delivered};

    sensors:
    - name: "Consumption Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "Consumption High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "Return Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "Return High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "Actual Consumption Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Actual Delivery Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Instant Voltage L1 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3
    - name: "Instant Voltage L2 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3
    - name: "Instant Voltage L3 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3
    - name: "Instant Current L1 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3
    - name: "Instant Current L2 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3
    - name: "Instant Current L3 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3
    - name: "Power Delivered L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Power Delivered L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Power Delivered L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Power Returned L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Power Returned L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Power Returned L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - multiply: 1000
    - name: "Gas device type Sensor"
    - name: "Gas valve position Sensor"
    - name: "Gas Meter M3 Sensor"
      unit_of_measurement: m3
      accuracy_decimals: 3

